### ISSUE TITLE
The reverse-proxy does not send content-type response header

### ISSUE THREAD

**Issue by vlad-ignatov** [smart-on-fhir/smart-stub#2]
Thanks to that the browsers treat the JSON response as text.

**Comment by nschwertner** [comment]
I didn't realize that the proxy alters the headers. I will investigate

**Comment by vlad-ignatov** [comment]
Might be because of the non-standard header that the DSTU2 server responds with.

**Comment by nschwertner** [comment]
Resolved by https://github.com/smart-on-fhir/smart-stub/commit/d59324839db41e4f5bbe1e6a1682ef4a6523cac0

**Comment by jmandel** [comment]
Wait, so what was the issue here?

**Comment by nschwertner** [comment]
The problem was a bug or feature in the reverse proxy of the SMART stub whereas it was not passing through or setting the content-type header. However, the conformance statement proxy, which is a separate component within the stub, was setting the content-type. When inspecting the HTTP headers of the stub, I was looking at the conformance statement call, but when when inspecting the headers from outside nginx I was looking at proxied resource calls. So I thought nginx was still clearing the content-type header after I added an explicit directive in its reverse proxy configuration to pass it through both ways. But, alas, it turned out to be a ghost chase within nginx while it was the stub that really wasn't setting the header.
